"use client";
import {FormEvent,useEffect,useRef,useState} from "react";
import {Check,Cpu,Heart,IndianRupee,Laptop,Loader2,Monitor,RefreshCw,Send,ShieldCheck,Sparkles,Wrench} from "lucide-react";
type Profile={budget:number;use:"gaming"|"creator"|"coding"|"everyday";kind:"custom"|"laptop"|"desktop";priority:"value"|"performance"|"upgrade"};
type Part={category:string;name:string;price:number;retailer:string;url:string;priceStatus?:"live"|"snapshot"};type Rec={title:string;total:number;parts:Part[];checks:string[];warnings:string[];priceCheckedAt:string};
const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n);
export default function Home(){const[p,setP]=useState<Profile>({budget:90000,use:"gaming",kind:"custom",priority:"value"}),[messages,setMessages]=useState([{role:"assistant",text:"Hi, I’m Kavi. Change any option in your brief and I’ll update my recommendation automatically. You can also ask a follow-up below."}]),[input,setInput]=useState("Build me a gaming PC under ₹90,000."),[rec,setRec]=useState<Rec|null>(null),[loading,setLoading]=useState(false),timer=useRef<ReturnType<typeof setTimeout>|null>(null),controller=useRef<AbortController|null>(null),requestNumber=useRef(0);
useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);controller.current?.abort()},[]);
const briefText=(profile:Profile)=>`Recommend a ${profile.priority==="value"?"best-value":profile.priority==="performance"?"maximum-performance":"upgrade-friendly"} ${profile.kind==="custom"?"custom PC":profile.kind} for ${profile.use} in India with a budget of ${money(profile.budget)}. Include compatibility, price status and product links.`;
const choose=<K extends keyof Profile>(key:K,value:Profile[K])=>{setP({...p,[key]:value});setRec(null)};const applyBrief=()=>requestRecommendation(briefText(p),p,false,`Brief submitted · ${p.kind} · ${p.use} · ${money(p.budget)} · ${p.priority}`);
async function requestRecommendation(text:string,profile:Profile,clearInput:boolean,userLabel=text){text=text.trim();if(!text)return;controller.current?.abort();const current=++requestNumber.current,aborter=new AbortController();controller.current=aborter;const history=[...messages,{role:"user",text:userLabel}];setMessages(history);if(clearInput)setInput("");setLoading(true);try{const response=await fetch("/api/agent",{method:"POST",headers:{"content-type":"application/json"},signal:aborter.signal,body:JSON.stringify({message:text,history:messages.slice(-6),profile})});const data=await response.json();if(!response.ok)throw Error(data.error);if(current===requestNumber.current){setMessages([...history,{role:"assistant",text:data.text}]);setRec(data.recommendation)}}catch(error){if(error instanceof DOMException&&error.name==="AbortError")return;if(current===requestNumber.current)setMessages([...history,{role:"assistant",text:error instanceof Error?error.message:"The advisor is temporarily unavailable."}])}finally{if(current===requestNumber.current)setLoading(false)}}
async function send(e?:FormEvent,text=input){e?.preventDefault();if(loading&&text===input)return;await requestRecommendation(text,p,true)}
const quick=[["Best value","Optimize this build for the best value."],["Check compatibility","Check every component for compatibility."],["Reduce price","Make this build cheaper without ruining performance."],["Plan upgrades","Make this build easy to upgrade later."]];return <main><header><a className="brand" href="#"><b>K</b><span>kind<strong>PC</strong></span></a><nav><a href="#advisor">AI advisor</a><a href="#recommendation">Recommendation</a><a href="#trust">Why KindPC</a></nav><button className="saved"><Heart/> Saved</button></header>
<section className="hero"><div className="hero-copy"><p className="eyebrow">SMARTER COMPUTER SHOPPING FOR INDIA</p><h1>Your perfect computer,<br/><em>without the confusion.</em></h1><p>Kavi compares your needs, budget, compatibility and market prices to recommend a computer you can buy with confidence.</p><div className="hero-actions"><button onClick={()=>document.getElementById("advisor")?.scrollIntoView()}>Start my recommendation <Sparkles/></button><a href="#trust">See how it works</a></div><div className="proof"><span><ShieldCheck/> Rule-checked compatibility</span><span><IndianRupee/> Indian prices</span><span><Heart/> Buyer-first advice</span></div></div><div className="hero-card"><div className="orb"><Cpu/></div><span>KAVI IS READY</span><h2>Tell me what you need.</h2><p>Gaming, study, coding, editing or everyday work.</p><div><i/><small>AI ADVISOR ONLINE</small></div></div></section>
<section className="advisor" id="advisor"><div className="chat"><div className="chat-head"><div className="avatar">K</div><div><b>Kavi</b><small><i/> Online · PC buying advisor</small></div><button onClick={()=>{setMessages(messages.slice(0,1));setRec(null)}}><RefreshCw/></button></div><div className="guided"><div className="guide-label"><span>K</span><div><small>KAVI · QUICK SETUP</small><b>Choose what you need</b><p>Tap the options below. I will update your recommendation automatically.</p></div></div><div className="preferences"><label>What are you buying?</label><div className="segmented">{[["custom","Custom PC",Wrench],["laptop","Laptop",Laptop],["desktop","Desktop",Monitor]].map(([v,t,I])=><button key={String(v)} className={p.kind===v?"active":""} onClick={()=>choose("kind",v as Profile["kind"])}><I/>{String(t)}</button>)}</div><label>Main use</label><div className="use-grid">{[["gaming","Gaming"],["creator","Editing & design"],["coding","Coding & AI"],["everyday","Study & everyday"]].map(([v,t])=><button key={v} className={p.use===v?"active":""} onClick={()=>choose("use",v as Profile["use"])}>{t}{p.use===v&&<Check/>}</button>)}</div><div className="budget-head"><label>Budget</label><strong>{money(p.budget)}</strong></div><div className="budget"><input aria-label="Budget" type="range" min="40000" max="250000" step="5000" value={p.budget} onChange={e=>choose("budget",Number(e.target.value))}/><small><span>₹40,000</span><span>₹2,50,000</span></small></div><label>Optimise for</label><div className="priority">{[["value","Best value"],["performance","Performance"],["upgrade","Upgrades"]].map(([v,t])=><button key={v} className={p.priority===v?"active":""} onClick={()=>choose("priority",v as Profile["priority"])}>{t}</button>)}</div><div className="brief"><Sparkles/><span><b>Review your brief</b><small>{loading?"Sending to Kavi…":`${p.kind} · ${p.use} · ${money(p.budget)} · press arrow to send`}</small></span><button aria-label="Send selected brief to Kavi" disabled={loading} onClick={applyBrief}><Send/></button></div></div></div><div className="messages">{messages.map((m,i)=><article className={m.role} key={i}>{m.role==="assistant"&&<span>K</span>}<div><small>{m.role==="assistant"?"KAVI":"YOU"}</small><p>{m.text}</p></div></article>)}{loading&&<article><span>K</span><div><small>KAVI</small><p className="thinking"><Loader2/> Checking products, prices and compatibility…</p></div></article>}</div><div className="quick">{quick.map(([label,prompt])=><button key={label} onClick={()=>send(undefined,prompt)}>{label}</button>)}</div><form onSubmit={send}><textarea aria-label="Message Kavi" value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask about a PC, laptop or component…" onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}}/><button disabled={loading||input.trim().length<2}><Send/></button><small>Kavi uses rules for compatibility and labels the age of every price.</small></form></div></section>
<section className="recommendation" id="recommendation"><div className="rec-title"><div><p className="eyebrow">YOUR RECOMMENDATION</p><h2>{rec?.title??"A clear answer will appear here."}</h2><p>{rec?"Products, direct store links and compatibility evidence in one place.":"Send Kavi your request to generate a tailored recommendation."}</p></div>{rec&&<strong>{money(rec.total)}</strong>}</div>{rec?<><div className="product-grid">{rec.parts.map((x,i)=><article key={x.category+x.name}><span>{String(i+1).padStart(2,"0")}</span><div><small>{x.category} · {x.priceStatus==="live"?"Live price":"Price snapshot"}</small><h3>{x.name}</h3><a href={x.url} target="_blank" rel="noreferrer">View product on {x.retailer} ↗</a></div><b>{money(x.price)}</b></article>)}</div><div className="report"><div><ShieldCheck/><h3>Compatibility report</h3>{rec.checks.map(x=><p key={x}><Check/> {x}</p>)}</div><div><Sparkles/><h3>Kavi’s notes</h3>{rec.warnings.map(x=><p key={x}>{x}</p>)}</div><footer>Price record: {new Date(rec.priceCheckedAt).toLocaleString("en-IN")} · Confirm checkout price and availability.</footer></div></>:<div className="empty"><div><Cpu/></div><h3>Ready when you are</h3><p>Your recommended products, prices and store links will appear here.</p></div>}</section>
<section className="trust" id="trust">{[["01","Recommendations with reasons","Every selection is explained in simple language."],["02","Compatibility before checkout","Sockets, memory, power and form factor are checked with rules."],["03","Transparent market data","Current prices and older snapshots are clearly distinguished."]].map(([n,h,c])=><article key={n}><span>{n}</span><h3>{h}</h3><p>{c}</p></article>)}</section><footer className="site-footer"><a className="brand" href="#"><b>K</b><span>kind<strong>PC</strong></span></a><p>Thoughtful computer advice, made for India.</p></footer></main>}


