"use client";
import {FormEvent,useState} from "react";import {Check,Cpu,Heart,IndianRupee,Laptop,Loader2,Monitor,RotateCcw,Send,ShieldCheck,Sparkles,Wrench} from "lucide-react";
type Profile={budget:number;use:"gaming"|"creator"|"coding"|"everyday";kind:"custom"|"laptop"|"desktop";priority:"value"|"performance"|"upgrade"};
type Part={category:string;name:string;price:number;retailer:string;url:string;priceStatus?:"live"|"snapshot"};
type Rec={title:string;total:number;parts:Part[];checks:string[];warnings:string[];priceCheckedAt:string};
const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n);
export default function Home(){
 const [p,setP]=useState<Profile>({budget:90000,use:"gaming",kind:"custom",priority:"value"}),[messages,setMessages]=useState([{role:"assistant",text:"Hi, I’m Kavi. Tell me what you want to play, create or build, and I’ll help you spend wisely."}]),[input,setInput]=useState("I need a PC for 1440p gaming and programming."),[rec,setRec]=useState<Rec|null>(null),[loading,setLoading]=useState(false);
 const choose=(key:keyof Profile,value:any)=>{setP(x=>({...x,[key]:value}));setRec(null)};
 async function send(e?:FormEvent,text=input){e?.preventDefault();text=text.trim();if(!text||loading)return;const history=[...messages,{role:"user",text}];setMessages(history);setInput("");setLoading(true);try{const r=await fetch("/api/agent",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({message:text,history:messages.slice(-6),profile:p})});const d=await r.json();if(!r.ok)throw Error(d.error);setMessages([...history,{role:"assistant",text:d.text}]);setRec(d.recommendation)}catch(err){setMessages([...history,{role:"assistant",text:err instanceof Error?err.message:"The advisor is temporarily unavailable."}])}finally{setLoading(false)}}
 return <main><header><a className="brand" href="#"><b>K</b>kind<span>PC</span></a><nav><a href="#advisor">AI advisor</a><a href="#build">Your build</a><a href="#trust">Trust</a></nav><button className="saved"><Heart/> Saved</button></header>
 <section className="hero"><div><p className="eyebrow">BUILT FOR INDIA</p><h1>A kinder way to choose your <em>next PC.</em></h1><p>Chat with an AI advisor that understands your work, games and budget—then checks every part before you buy.</p><div className="badges"><span><ShieldCheck/> Compatibility checked</span><span><IndianRupee/> Prices in INR</span><span><Sparkles/> Gemini powered</span></div></div><div className="chip"><Cpu/><small>SMART MATCH</small><b>AM5</b></div></section>
 <section className="shell" id="advisor"><aside><label>WHAT ARE YOU BUYING?</label><div className="choices">{[["custom","Custom PC",Wrench],["laptop","Laptop",Laptop],["desktop","Desktop",Monitor]].map(([v,t,I]:any)=><button className={p.kind===v?"on":""} onClick={()=>choose("kind",v)} key={v}><I/>{t}</button>)}</div><label>MAIN USE</label><div className="grid">{[["gaming","Gaming"],["creator","Editing & design"],["coding","Coding & AI"],["everyday","Study & everyday"]].map(([v,t])=><button className={p.use===v?"on":""} onClick={()=>choose("use",v)} key={v}>{t}{p.use===v&&<Check/>}</button>)}</div><label>BUDGET</label><div className="budget"><strong>{money(p.budget)}</strong><input aria-label="Budget" type="range" min="40000" max="250000" step="5000" value={p.budget} onChange={e=>choose("budget",+e.target.value)}/><small><span>₹40k</span><span>₹2.5L</span></small></div><label>OPTIMISE FOR</label><div className="tabs">{[["value","Best value"],["performance","Speed"],["upgrade","Upgrades"]].map(([v,t])=><button className={p.priority===v?"on":""} onClick={()=>choose("priority",v)} key={v}>{t}</button>)}</div><div className="brief"><Sparkles/><p><b>Kavi knows your brief.</b><br/>{p.kind} · {p.use} · {money(p.budget)}</p></div></aside>
 <div className="chat"><div className="chathead"><div className="avatar">K<i/></div><div><h2>Kavi, your PC advisor</h2><p>● Online · Verified catalogue tools</p></div><button onClick={()=>{setMessages(messages.slice(0,1));setRec(null)}}><RotateCcw/></button></div><div className="messages">{messages.map((m,i)=><article className={m.role} key={i}>{m.role==="assistant"&&<span>K</span>}<div><small>{m.role==="assistant"?"KAVI":"YOU"}</small><p>{m.text}</p></div></article>)}{loading&&<article><span>K</span><div><small>KAVI</small><p className="thinking"><Loader2/> Checking products and compatibility…</p></div></article>}</div><div className="prompts">{["Can it run modern games?","Make it easier to upgrade","Explain the GPU choice"].map(x=><button onClick={()=>send(undefined,x)} key={x}>{x}</button>)}</div><form onSubmit={send}><textarea aria-label="Message Kavi" value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask about a computer or component…" onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}}/><button disabled={loading||input.trim().length<2}><Send/></button><small>AI can make mistakes. Compatibility is checked by rules.</small></form></div></section>
 <section className="build" id="build"><div className="buildtop"><div><p className="eyebrow">MARKET RECOMMENDATION</p><h2>{rec?.title??"Your matched build will appear here."}</h2><p>{rec?"Every item includes its price status, direct product link and compatibility evidence.":"Send Kavi a message to create your tailored recommendation."}</p></div>{rec&&<strong>{money(rec.total)}</strong>}</div>{rec?<><div className="parts">{rec.parts.map((x,i)=><article key={x.category}><span>{String(i+1).padStart(2,"0")}</span><div><small>{x.category} · {x.priceStatus==="live"?"LIVE PRICE":"PRICE SNAPSHOT"}</small><h3>{x.name}</h3><a href={x.url} target="_blank" rel="noreferrer">View product on {x.retailer} ↗</a></div><b>{money(x.price)}</b></article>)}</div><div className="report"><div><ShieldCheck/><h3>Compatibility report</h3>{rec.checks.map(x=><p key={x}>✓ {x}</p>)}</div><div><h3>Before you order</h3>{rec.warnings.map(x=><p key={x}>{x}</p>)}</div><footer>{rec.parts.some(x=>x.priceStatus==="live")?"Retailer checked":"Snapshot recorded"} {new Date(rec.priceCheckedAt).toLocaleString("en-IN")} · Confirm the checkout price and stock before payment.</footer></div></>:<div className="empty"><Cpu/><h3>No build yet</h3><p>Parts, current catalogue prices, retailer links and checks will appear here.</p></div>}</section>
 <section className="trust" id="trust">{[["01","Facts come from tools","Kavi uses a structured catalogue instead of inventing specifications."],["02","Rules guard compatibility","Socket, memory, wattage and form factor are checked outside the model."],["03","Prices show their age","Every result includes its source and the time it was last checked."]].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</section><footer className="sitefoot"><a className="brand" href="#"><b>K</b>kind<span>PC</span></a><p>Thoughtful computer advice, made for India.</p></footer></main>}
