"use client";
import {FormEvent,useEffect,useState} from "react";
import {Check,ChevronRight,Heart,Loader2,Maximize2,RotateCcw,Send,ShieldCheck,Sparkles,TriangleAlert} from "lucide-react";
import Workshop3D,{ComponentKey} from "../components/workshop/Workshop3D";
import {BuildHud,ComponentRail} from "../components/workshop/BuildUI";
type Profile={budget:number;use:"gaming"|"creator"|"coding"|"everyday";kind:"custom"|"laptop"|"desktop";priority:"value"|"performance"|"upgrade"};
type Part={category:string;name:string;price:number;retailer:string;url:string;priceStatus?:"live"|"snapshot"};type Rec={title:string;total:number;parts:Part[];checks:string[];warnings:string[];priceCheckedAt:string};
const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n);
const topic=(text:string):ComponentKey=>{const t=text.toLowerCase();if(/graphics|gpu|fps|gaming/.test(t))return"gpu";if(/ram|memory/.test(t))return"ram";if(/cool|fan|thermal/.test(t))return"cooling";if(/power|psu|watt/.test(t))return"psu";if(/storage|ssd|nvme/.test(t))return"storage";if(/motherboard|socket|bios/.test(t))return"motherboard";if(/case|clearance|chassis/.test(t))return"case";return"cpu"};
export default function Home(){
 const[p,setP]=useState<Profile>({budget:90000,use:"gaming",kind:"custom",priority:"value"}),[messages,setMessages]=useState([{role:"assistant",text:"Systems online. Tell me what you play, create or build, and I’ll engineer a balanced machine."}]),[input,setInput]=useState("Build me a gaming PC under ₹90,000."),[rec,setRec]=useState<Rec|null>(null),[loading,setLoading]=useState(false),[selected,setSelected]=useState<ComponentKey>("gpu"),[exploded,setExploded]=useState(false),[intro,setIntro]=useState(false),[consoleOpen,setConsoleOpen]=useState(true);
 useEffect(()=>{const timer=window.setTimeout(()=>{if(!sessionStorage.getItem("kindpc-intro")){setIntro(true);sessionStorage.setItem("kindpc-intro","seen")}},0);return()=>window.clearTimeout(timer)},[]);
 const choose=<K extends keyof Profile>(key:K,value:Profile[K])=>{setP(x=>({...x,[key]:value}));setRec(null)};
 async function send(e?:FormEvent,text=input){e?.preventDefault();text=text.trim();if(!text||loading)return;setSelected(topic(text));const history=[...messages,{role:"user",text}];setMessages(history);setInput("");setLoading(true);try{const r=await fetch("/api/agent",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({message:text,history:messages.slice(-6),profile:p})});const d=await r.json();if(!r.ok)throw Error(d.error);setMessages([...history,{role:"assistant",text:d.text}]);setRec(d.recommendation);setSelected(topic(d.text));}catch(err){setMessages([...history,{role:"assistant",text:err instanceof Error?err.message:"The advisor is temporarily unavailable."}])}finally{setLoading(false)}}
 const quick=[["OPTIMIZE BUILD","Optimize this build for the best value."],["CHECK COMPATIBILITY","Check every component for compatibility."],["REDUCE PRICE","Make this build cheaper without ruining performance."],["MAXIMIZE FPS","Maximize gaming FPS within my budget."],["IMPROVE COOLING","Improve cooling and explain the thermal choices."],["PLAN UPGRADES","Make this build easy to upgrade later."]];
 return <main className="lab">{intro&&<div className="intro"><div className="intro-core"><i/><i/><b>K</b></div><p>KINDPC SYSTEM // ONLINE</p><h1>BUILD SMARTER.<br/>SEE EVERY COMPONENT.<br/><em>LET AI ENGINEER YOUR PC.</em></h1><div><button onClick={()=>{setIntro(false);setConsoleOpen(true)}}>START AI BUILD <ChevronRight/></button><button onClick={()=>setIntro(false)}>EXPLORE PC</button></div><small>Click anywhere outside the controls to skip</small></div>}
 <header className="labhead"><a className="labbrand" href="#"><b>K</b><span>KIND<strong>PC</strong></span><small>AI HARDWARE ARCHITECT</small></a><nav><a href="#workshop">WORKSHOP</a><a href="#intelligence">INTELLIGENCE</a><a href="#market">MARKET</a></nav><button className="saved"><Heart/> SAVED</button></header>
 <section className="commandbar"><div><span className="status-dot"/> WORKSHOP ONLINE</div><p>BUILD MODE / <b>{p.kind.toUpperCase()}</b></p><button onClick={()=>setExploded(x=>!x)} className={exploded?"active":""}><Maximize2/>{exploded?"ASSEMBLE":"EXPLODED VIEW"}</button></section>
 <section className="workshop" id="workshop"><ComponentRail selected={selected} onSelect={setSelected}/><div className="scene"><Workshop3D selected={selected} exploded={exploded} aiState={loading?"thinking":rec?"success":"idle"}/><div className="scene-title"><small>LIVE HARDWARE VIEW</small><h1>{selected.toUpperCase()}</h1><p>SELECTED MODULE // Click hardware to inspect</p></div></div>
 <aside className={`console ${consoleOpen?"open":""}`}><div className="console-head"><div className={`ai-mark ${loading?"thinking":""}`}><i/><b>K</b></div><div><strong>KAVI</strong><small>{loading?"ANALYZING HARDWARE":"AI BUILD ENGINEER · READY"}</small></div><button onClick={()=>setConsoleOpen(x=>!x)}>{consoleOpen?"−":"+"}</button></div>{consoleOpen&&<><div className="profile"><label>MISSION</label><div>{[["gaming","GAMING"],["creator","CREATION"],["coding","CODING"],["everyday","EVERYDAY"]].map(([v,t])=><button key={v} className={p.use===v?"active":""} onClick={()=>choose("use",v)}>{t}</button>)}</div><label>BUDGET <b>{money(p.budget)}</b></label><input type="range" min="40000" max="250000" step="5000" value={p.budget} onChange={e=>choose("budget",+e.target.value)}/><div className="mode-row">{[["custom","CUSTOM PC"],["laptop","LAPTOP"],["desktop","PREBUILT"]].map(([v,t])=><button key={v} className={p.kind===v?"active":""} onClick={()=>choose("kind",v)}>{t}</button>)}</div></div><div className="messages">{messages.slice(-4).map((m,i)=><article className={m.role} key={i}>{m.role==="assistant"&&<span>K</span>}<div><small>{m.role==="assistant"?"KAVI":"YOU"}</small><p>{m.text}</p></div></article>)}{loading&&<article><span>K</span><div><small>KAVI</small><p className="thinking"><Loader2/> Inspecting market and compatibility…</p></div></article>}</div><div className="quick">{quick.map(([a,b])=><button key={a} onClick={()=>send(undefined,b)}>{a}</button>)}</div><form onSubmit={send}><textarea aria-label="Message Kavi" value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask your PC architect anything..." onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}}/><button disabled={loading||input.trim().length<2}><Send/></button></form></>}</aside></section>
 <BuildHud total={rec?.total??0} selected={selected} compatible={Boolean(rec)}/>
 <section className="intelligence" id="intelligence"><div className="intel-head"><p>BUILD INTELLIGENCE</p><h2>{rec?.title??"Your engineered system will appear here."}</h2><span>{rec?money(rec.total):"AWAITING COMMAND"}</span></div>{rec?<div className="intel-grid"><div className="product-list">{rec.parts.map((x,i)=><button key={x.category+x.name} onClick={()=>setSelected(topic(x.category))}><i>{String(i+1).padStart(2,"0")}</i><span><small>{x.category} · {x.priceStatus==="live"?"LIVE PRICE":"PRICE SNAPSHOT"}</small><b>{x.name}</b><a href={x.url} target="_blank" rel="noreferrer" onClick={e=>e.stopPropagation()}>VIEW ON {x.retailer.toUpperCase()} ↗</a></span><strong>{money(x.price)}</strong></button>)}</div><div className="diagnostics"><div><ShieldCheck/><h3>COMPATIBILITY PASSED</h3>{rec.checks.map(x=><p key={x}><Check/> {x}</p>)}</div><div><TriangleAlert/><h3>ENGINEER NOTES</h3>{rec.warnings.map(x=><p key={x}>{x}</p>)}</div><footer>MARKET DATA · {new Date(rec.priceCheckedAt).toLocaleString("en-IN")} · Confirm checkout price and stock.</footer></div></div>:<div className="awaiting"><Sparkles/><p>Tell Kavi your budget and workload. The selected parts, compatibility evidence, retailer links and market status will populate here.</p></div>}</section>
 <footer className="labfoot"><span>KINDPC // INDIA</span><p>AI-assisted decisions. Rule-checked compatibility. Transparent market status.</p><button onClick={()=>{setMessages(messages.slice(0,1));setRec(null)}}><RotateCcw/> RESET WORKSHOP</button></footer></main>}

