"use client";
import {Canvas,useFrame,useThree} from "@react-three/fiber";
import {ContactShadows,Grid,OrbitControls,Text} from "@react-three/drei";
import {useEffect,useRef,useState} from "react";
import * as THREE from "three";
export type ComponentKey="cpu"|"gpu"|"motherboard"|"ram"|"storage"|"psu"|"cooling"|"case";
type Props={selected:ComponentKey;exploded:boolean;aiState:"idle"|"thinking"|"responding"|"success";onSelect:(key:ComponentKey)=>void};
type PartProps={id:ComponentKey;selected:ComponentKey;exploded:boolean;assembled:[number,number,number];explodedAt:[number,number,number];onSelect:(key:ComponentKey)=>void;children:React.ReactNode};
const metal="#24282c",dark="#111416",board="#26312f",accent="#ef9a57",glass="#a7c6c0";
function Part({id,selected,exploded,assembled,explodedAt,onSelect,children}:PartProps){const group=useRef<THREE.Group>(null),active=id===selected;useFrame((_,delta)=>{if(!group.current)return;const target=exploded?explodedAt:assembled;group.current.position.lerp(new THREE.Vector3(...target),Math.min(1,delta*5));group.current.scale.lerp(new THREE.Vector3(active?1.035:1,active?1.035:1,active?1.035:1),Math.min(1,delta*7))});return <group ref={group} position={assembled} onClick={e=>{e.stopPropagation();onSelect(id)}}>{children}{active&&<pointLight color={accent} intensity={4} distance={2}/>}</group>}
function Fan({position,rotation=[Math.PI/2,0,0]}:{position:[number,number,number];rotation?:[number,number,number]}){const blades=useRef<THREE.Group>(null);useFrame((_,d)=>{if(blades.current)blades.current.rotation.z+=d*2.4});return <group position={position} rotation={rotation}><mesh><cylinderGeometry args={[.36,.36,.09,32]}/><meshStandardMaterial color="#171b1e" metalness={.7} roughness={.25}/></mesh><group ref={blades}>{[0,1,2,3,4,5].map(i=><mesh key={i} rotation={[0,0,i*Math.PI/3]} position={[.15,0,.06]}><boxGeometry args={[.25,.07,.035]}/><meshStandardMaterial color="#77817f" metalness={.55}/></mesh>)}</group><mesh position={[0,0,.08]}><torusGeometry args={[.28,.025,8,32]}/><meshStandardMaterial color={accent} emissive={accent} emissiveIntensity={.25}/></mesh></group>}
function CameraRig({selected}:{selected:ComponentKey}){const{camera}=useThree();useEffect(()=>{const views:Partial<Record<ComponentKey,[number,number,number]>>={gpu:[4.4,.35,5.4],cpu:[4.1,1.3,5.1],ram:[4.3,1.2,5.1],psu:[4,-1.1,5.3],cooling:[4.2,2,5.2],case:[5.5,.8,7]};camera.position.lerp(new THREE.Vector3(...(views[selected]??[4.7,.8,5.8])),.45);camera.lookAt(0,.25,0)},[selected,camera]);return null}
function Tower(props:Props){const material=(active:boolean,color:string)=> <meshStandardMaterial color={active?accent:color} metalness={.68} roughness={.3} emissive={active?accent:"#000"} emissiveIntensity={active?.18:0}/>;return <group rotation={[0,-.18,0]}>
 <Part id="case" selected={props.selected} exploded={props.exploded} assembled={[0,0,0]} explodedAt={[0,0,-.8]} onSelect={props.onSelect}><mesh position={[0,0,-.52]}><boxGeometry args={[3.45,4.7,.12]}/>{material(props.selected==="case",dark)}</mesh><mesh position={[-1.67,0,0]}><boxGeometry args={[.12,4.7,1.18]}/>{material(false,metal)}</mesh><mesh position={[1.67,0,0]}><boxGeometry args={[.12,4.7,1.18]}/>{material(false,metal)}</mesh><mesh position={[0,2.29,0]}><boxGeometry args={[3.45,.12,1.18]}/>{material(false,metal)}</mesh><mesh position={[0,-2.29,0]}><boxGeometry args={[3.45,.12,1.18]}/>{material(false,metal)}</mesh><mesh position={[0,0,.58]}><boxGeometry args={[3.32,4.55,.025]}/><meshPhysicalMaterial color={glass} transparent opacity={.09} roughness={.08} transmission={.72}/></mesh></Part>
 <Part id="motherboard" selected={props.selected} exploded={props.exploded} assembled={[0,.25,-.34]} explodedAt={[-2.7,.3,.25]} onSelect={props.onSelect}><mesh><boxGeometry args={[2.55,3.05,.1]}/>{material(props.selected==="motherboard",board)}</mesh>{[-.8,0,.8].map(x=><mesh key={x} position={[x,-.7,.08]}><boxGeometry args={[.34,.12,.05]}/><meshStandardMaterial color="#a4875e" metalness={.8}/></mesh>)}</Part>
 <Part id="cpu" selected={props.selected} exploded={props.exploded} assembled={[-.25,.78,-.2]} explodedAt={[-.25,2.8,1.1]} onSelect={props.onSelect}><mesh><boxGeometry args={[.62,.62,.11]}/>{material(props.selected==="cpu","#aab1ad")}</mesh><mesh position={[0,0,.14]}><boxGeometry args={[.5,.5,.16]}/><meshStandardMaterial color="#4b5353" metalness={.8}/></mesh></Part>
 <Part id="ram" selected={props.selected} exploded={props.exploded} assembled={[.62,.75,-.1]} explodedAt={[2.6,1.4,.6]} onSelect={props.onSelect}>{[-.14,.14].map(x=><mesh key={x} position={[x,0,0]}><boxGeometry args={[.16,1.22,.12]}/>{material(props.selected==="ram","#394440")}</mesh>)}</Part>
 <Part id="storage" selected={props.selected} exploded={props.exploded} assembled={[-.72,-.1,-.08]} explodedAt={[-2.6,-.8,.7]} onSelect={props.onSelect}><mesh><boxGeometry args={[.25,.86,.09]}/>{material(props.selected==="storage","#8b765a")}</mesh></Part>
 <Part id="gpu" selected={props.selected} exploded={props.exploded} assembled={[.05,-.52,.18]} explodedAt={[2.9,-.3,1.1]} onSelect={props.onSelect}><mesh><boxGeometry args={[2.55,.72,.48]}/>{material(props.selected==="gpu","#252a2d")}</mesh>{[-.62,.22,.68].map(x=><group key={x} position={[x,0,.27]} rotation={[Math.PI/2,0,0]}><mesh><torusGeometry args={[.22,.04,10,28]}/><meshStandardMaterial color="#69716f" metalness={.75}/></mesh><mesh><circleGeometry args={[.08,20]}/><meshStandardMaterial color={accent}/></mesh></group>)}</Part>
 <Part id="psu" selected={props.selected} exploded={props.exploded} assembled={[0,-1.72,-.05]} explodedAt={[0,-3.25,.7]} onSelect={props.onSelect}><mesh><boxGeometry args={[2.55,.73,.85]}/>{material(props.selected==="psu","#15191b")}</mesh><Text position={[0,0,.44]} fontSize={.14} color="#b6bfbb">750W GOLD</Text></Part>
 <Part id="cooling" selected={props.selected} exploded={props.exploded} assembled={[0,1.82,0]} explodedAt={[0,3.25,.8]} onSelect={props.onSelect}><mesh><boxGeometry args={[2.3,.2,.65]}/>{material(props.selected==="cooling","#30373a")}</mesh><Fan position={[-.55,-.18,.05]}/><Fan position={[.55,-.18,.05]}/></Part>
 <Fan position={[1.36,.95,-.15]} rotation={[Math.PI/2,0,0]}/><Fan position={[1.36,.05,-.15]} rotation={[Math.PI/2,0,0]}/>
 </group>}
function Core({state}:{state:Props["aiState"]}){const g=useRef<THREE.Group>(null);useFrame(({clock},d)=>{if(g.current){g.current.rotation.y+=d*(state==="thinking"?2:.35);g.current.position.y=1.7+Math.sin(clock.elapsedTime*1.4)*.07}});return <group ref={g} position={[-2.65,1.7,.8]}><mesh><icosahedronGeometry args={[.21,1]}/><meshStandardMaterial color={accent} emissive={accent} emissiveIntensity={1.2}/></mesh>{[.36,.48,.6].map((r,i)=><mesh key={r} rotation={[i*.7,i,0]}><torusGeometry args={[r,.025,8,32]}/><meshStandardMaterial color="#9caaa6" metalness={.9}/></mesh>)}</group>}
export default function Workshop3D(props:Props){const[webgl,setWebgl]=useState(true);return <div className="viewport"><div className={`tower-blueprint ${props.exploded?"is-exploded":""}`} aria-hidden="true"><div className="bp-case"><i className="bp-board"/><i className="bp-cpu"/><i className="bp-ram one"/><i className="bp-ram two"/><i className="bp-gpu"><b/><b/><b/></i><i className="bp-psu">750W</i><i className="bp-rad"/><i className="bp-fan f1"/><i className="bp-fan f2"/><span>GLASS SIDE PANEL</span></div></div>{webgl?<Canvas dpr={[1,1.45]} camera={{position:[4.7,.8,5.8],fov:38}} gl={{antialias:true,alpha:true,powerPreference:"high-performance"}} onCreated={({gl})=>gl.domElement.addEventListener("webglcontextlost",()=>setWebgl(false))}><ambientLight intensity={1.25}/><directionalLight position={[4,6,6]} intensity={3.2} color="#fff4ea"/><pointLight position={[-4,1,3]} intensity={12} color={accent}/><Tower {...props}/><Core state={props.aiState}/><ContactShadows position={[0,-2.37,0]} opacity={.55} scale={8} blur={2.5}/><Grid position={[0,-2.36,0]} args={[14,14]} cellColor="#302c29" sectionColor="#5e4433" fadeDistance={9}/><CameraRig selected={props.selected}/><OrbitControls enablePan={false} minDistance={4.4} maxDistance={8.5} target={[0,.15,0]}/></Canvas>:<div className="webgl-fallback"><div className="fallback-tower">3D preview unavailable</div><p>Build controls and Kavi remain fully usable.</p></div>}<div className="viewhint">DRAG TO ROTATE · SCROLL TO ZOOM · SELECT HARDWARE</div></div>}

