"use client";
import {Canvas,useFrame,useThree} from "@react-three/fiber";
import {Grid,OrbitControls,Text} from "@react-three/drei";
import {Suspense,useEffect,useRef,useState} from "react";
import * as THREE from "three";
export type ComponentKey="cpu"|"gpu"|"motherboard"|"ram"|"storage"|"psu"|"cooling"|"case";
type Props={selected:ComponentKey;exploded:boolean;aiState:"idle"|"thinking"|"responding"|"success";onSelect:(key:ComponentKey)=>void};
type PartSpec={key:ComponentKey;pos:[number,number,number];size:[number,number,number];color:string;label:string};
const parts:PartSpec[]=[
 {key:"motherboard",pos:[0,.25,0],size:[2.65,3.15,.12],color:"#24333b",label:"MOTHERBOARD"},{key:"cpu",pos:[0,.65,.18],size:[.62,.62,.18],color:"#b7c6bd",label:"CPU"},{key:"ram",pos:[.78,.65,.22],size:[.14,1.2,.16],color:"#38d6aa",label:"RAM"},{key:"gpu",pos:[0,-.35,.48],size:[2.3,.68,.42],color:"#17252d",label:"GPU"},{key:"storage",pos:[-.77,.62,.25],size:[.25,.82,.13],color:"#d59655",label:"NVMe"},{key:"psu",pos:[0,-1.45,.15],size:[1.65,.6,.9],color:"#111a20",label:"PSU"},{key:"cooling",pos:[0,1.48,.34],size:[1.35,.18,.52],color:"#45616a",label:"COOLING"}];
function CameraRig({selected}:{selected:ComponentKey}){const{camera}=useThree();useEffect(()=>{camera.position.lerp(new THREE.Vector3(selected==="gpu"?3.8:selected==="psu"?-3.4:4.7,selected==="cooling"?2.5:1.4,selected==="case"?6.8:5.7),.35);camera.lookAt(0,0,0)},[selected,camera]);return null}
function HardwarePart({part,selected,exploded,onSelect}:{part:PartSpec;selected:ComponentKey;exploded:boolean;onSelect:(key:ComponentKey)=>void}){const ref=useRef<THREE.Mesh>(null);const active=selected===part.key;useFrame((_,d)=>{if(!ref.current)return;const target=(exploded?part.pos.map(v=>v*1.55):part.pos) as [number,number,number];ref.current.position.lerp(new THREE.Vector3(...target),Math.min(1,d*5));ref.current.rotation.z=THREE.MathUtils.lerp(ref.current.rotation.z,active?.04:0,d*5)});return <group><mesh ref={ref} position={part.pos} onClick={e=>{e.stopPropagation();onSelect(part.key)}} onPointerOver={e=>{e.stopPropagation();document.body.style.cursor="pointer"}} onPointerOut={()=>document.body.style.cursor="auto"}><boxGeometry args={part.size}/><meshStandardMaterial color={active?"#54f4c2":part.color} metalness={.72} roughness={.28} emissive={active?"#1ad99f":"#000"} emissiveIntensity={active?.75:0}/></mesh>{active&&<Text position={[part.pos[0],part.pos[1]+part.size[1]/2+.25,.7]} fontSize={.13} color="#8fffdc" anchorX="center">{part.label}</Text>}</group>}
function Chassis({exploded,selected,onSelect}:Pick<Props,"exploded"|"selected"|"onSelect">){const rails:[number,number,number][]=[[-1.48,0,.25],[1.48,0,.25]];return <group><mesh position={[0,0,-.28]} onClick={()=>onSelect("case")}><boxGeometry args={[3.35,4.3,.12]}/><meshStandardMaterial color={selected==="case"?"#37ddb0":"#111a20"} metalness={.82} roughness={.23}/></mesh>{rails.map((position,i)=><mesh key={i} position={position}><boxGeometry args={[.1,4.1,.75]}/><meshStandardMaterial color="#33454d" metalness={.8}/></mesh>)}{parts.map(part=><HardwarePart key={part.key} part={part} selected={selected} exploded={exploded} onSelect={onSelect}/>)}</group>}
function Core({state}:{state:Props["aiState"]}){const g=useRef<THREE.Group>(null);useFrame(({clock},d)=>{if(g.current){g.current.rotation.y+=d*(state==="thinking"?2.2:.45);g.current.position.y=1.65+Math.sin(clock.elapsedTime*1.5)*.08}});return <group ref={g} position={[-2.8,1.65,1]}><mesh><icosahedronGeometry args={[.24,1]}/><meshStandardMaterial color="#70ffd4" emissive="#20dba7" emissiveIntensity={state==="idle"?1:2.4}/></mesh>{[0,.75,1.5].map((r,i)=><mesh key={i} rotation={[r,r/2,r]}><torusGeometry args={[.42+i*.09,.045,8,24]}/><meshStandardMaterial color="#7b9299" metalness={.9} emissive={state==="thinking"?"#25e8b3":"#000"}/></mesh>)}</group>}
export default function Workshop3D(props:Props){const[webgl,setWebgl]=useState(true);return <div className="viewport">{webgl?<Canvas dpr={[1,1.5]} camera={{position:[4.7,1.4,5.7],fov:38}} gl={{antialias:true,powerPreference:"high-performance"}} onCreated={({gl})=>gl.domElement.addEventListener("webglcontextlost",()=>setWebgl(false))}><color attach="background" args={["#070b0e"]}/><fog attach="fog" args={["#070b0e",8,16]}/><ambientLight intensity={.45}/><spotLight position={[3,6,5]} intensity={65} angle={.38} color="#d8fff4" castShadow/><pointLight position={[-4,1,3]} intensity={18} color="#2be8b3"/><Suspense fallback={null}><Chassis {...props}/><Core state={props.aiState}/><Grid position={[0,-2.18,0]} args={[16,16]} cellColor="#1b3834" sectionColor="#275f54" fadeDistance={10}/></Suspense><CameraRig selected={props.selected}/><OrbitControls enablePan={false} minDistance={4} maxDistance={9} target={[0,0,0]} autoRotate={props.aiState==="idle"} autoRotateSpeed={.35}/></Canvas>:<div className="webgl-fallback">3D preview unavailable. Build controls and AI remain active.</div>}<div className="viewhint">DRAG TO ROTATE · SCROLL TO ZOOM · SELECT HARDWARE</div></div>}

